package github2;

import org.junit.Test;

/*
 * try-catch-finally中finally的使用：
 * 
 * 1.finally是可选的。
 * 2.finally中声明的是一定会被执行的代码。即使catch中又出现异常了，try中有return语句，catch中有
 *   return语句等情况。
 * 3.
 * 
 */
public class FinallyTest {

	@Test
	public void test1(){
		try {			
			int a = 10;
			int b = 0;
			System.out.println(a / b);
		} catch (ArithmeticException e) {
//			e.printStackTrace();
			
			int[] arr = new int[10];
			System.out.println(arr[10]);
			
		}catch(Exception e){
			e.printStackTrace();
		}
//		System.out.println("我好慢呀~~~");
		finally{
			System.out.println("我好慢呀~~~");
		}
	}
}
